// Action types

//types.js

export const SET_GLOBAL_LOADING = 'SET_GLOBAL_LOADING';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT = 'LOGOUT_REQUEST';


export const USER_SET_UUID = 'USER_SET_UUID';
export const PROFILE_SET_UUID = 'PROFILE_SET_UUID';
export const SET_USER_PHOTO = 'SET_USER_PHOTO';

export const SET_BASE64_DATA = 'SET_BASE64_DATA';

export const SET_USER_PROFILE_POSTS = 'SET_USER_PROFILE_POSTS';
